# Generated by Django 5.2.1 on 2025-05-27 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_document_content'),
        ('documents', 'add_content_field'),
    ]

    operations = [
    ]
