# Generated by Django 5.0.2 on 2025-05-28 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_merge_0004_document_content_add_content_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='is_favorite',
        ),
        migrations.RemoveField(
            model_name='document',
            name='shared_with',
        ),
    ]
